[package]
name = "datajoint-core-ffi-c"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/datajoint/datajoint-core"

[lib]
crate-type = ["cdylib"]
name="corelib"

[build-dependencies]
cbindgen = "0.20.0"

[dependencies]
datajoint-core = { path = "../datajoint-core" }
libc = "0.2.101"
num-derive = "0.3.3"
num-traits = "0.2.1"
