[package]
name = "datajoint-core"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/datajoint/datajoint-core"

[dependencies]
futures = { version = "0.3.1" }
futures-core = { version = "0.3.1" }
thiserror = "1.0.19"
tokio = { version = "1.11.0", features = ["full"] }
sqlx = { version = "0.5", features = ["runtime-async-std-native-tls", "postgres", "mysql", "tls", "any"]}
